CREATE TABLE IF NOT EXISTS orders(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  delivery INTEGER NOT NULL,
  payment INTEGER NOT NULL,
  order_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (delivery) REFERENCES delivery (id) ON DELETE CASCADE,
  FOREIGN KEY (payment) REFERENCES payment (id) ON DELETE CASCADE
);
