CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE,
  phone INTEGER NOT NULL UNIQUE,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
